
package it.car2go.servant.prenotazione;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrenotazioneService", targetNamespace = "http://prenotazione.servant.car2go.it/", wsdlLocation = "http://imac-di-francesco.local:8080/car2go-soapws/PrenotazioneService?wsdl")
public class PrenotazioneService
    extends Service
{

    private final static URL PRENOTAZIONESERVICE_WSDL_LOCATION;
    private final static WebServiceException PRENOTAZIONESERVICE_EXCEPTION;
    private final static QName PRENOTAZIONESERVICE_QNAME = new QName("http://prenotazione.servant.car2go.it/", "PrenotazioneService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://imac-di-francesco.local:8080/car2go-soapws/PrenotazioneService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRENOTAZIONESERVICE_WSDL_LOCATION = url;
        PRENOTAZIONESERVICE_EXCEPTION = e;
    }

    public PrenotazioneService() {
        super(__getWsdlLocation(), PRENOTAZIONESERVICE_QNAME);
    }

    public PrenotazioneService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRENOTAZIONESERVICE_QNAME, features);
    }

    public PrenotazioneService(URL wsdlLocation) {
        super(wsdlLocation, PRENOTAZIONESERVICE_QNAME);
    }

    public PrenotazioneService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRENOTAZIONESERVICE_QNAME, features);
    }

    public PrenotazioneService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrenotazioneService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrenotazioneServant
     */
    @WebEndpoint(name = "PrenotazioneServantPort")
    public PrenotazioneServant getPrenotazioneServantPort() {
        return super.getPort(new QName("http://prenotazione.servant.car2go.it/", "PrenotazioneServantPort"), PrenotazioneServant.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrenotazioneServant
     */
    @WebEndpoint(name = "PrenotazioneServantPort")
    public PrenotazioneServant getPrenotazioneServantPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://prenotazione.servant.car2go.it/", "PrenotazioneServantPort"), PrenotazioneServant.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRENOTAZIONESERVICE_EXCEPTION!= null) {
            throw PRENOTAZIONESERVICE_EXCEPTION;
        }
        return PRENOTAZIONESERVICE_WSDL_LOCATION;
    }

}
