
package it.car2go.servant.macchina;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MacchinaService", targetNamespace = "http://macchina.servant.car2go.it/", wsdlLocation = "http://imac-di-francesco.local:8080/car2go-soapws/MacchinaService?wsdl")
public class MacchinaService
    extends Service
{

    private final static URL MACCHINASERVICE_WSDL_LOCATION;
    private final static WebServiceException MACCHINASERVICE_EXCEPTION;
    private final static QName MACCHINASERVICE_QNAME = new QName("http://macchina.servant.car2go.it/", "MacchinaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://imac-di-francesco.local:8080/car2go-soapws/MacchinaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MACCHINASERVICE_WSDL_LOCATION = url;
        MACCHINASERVICE_EXCEPTION = e;
    }

    public MacchinaService() {
        super(__getWsdlLocation(), MACCHINASERVICE_QNAME);
    }

    public MacchinaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MACCHINASERVICE_QNAME, features);
    }

    public MacchinaService(URL wsdlLocation) {
        super(wsdlLocation, MACCHINASERVICE_QNAME);
    }

    public MacchinaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MACCHINASERVICE_QNAME, features);
    }

    public MacchinaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MacchinaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MacchinaServant
     */
    @WebEndpoint(name = "MacchinaServantPort")
    public MacchinaServant getMacchinaServantPort() {
        return super.getPort(new QName("http://macchina.servant.car2go.it/", "MacchinaServantPort"), MacchinaServant.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MacchinaServant
     */
    @WebEndpoint(name = "MacchinaServantPort")
    public MacchinaServant getMacchinaServantPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://macchina.servant.car2go.it/", "MacchinaServantPort"), MacchinaServant.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MACCHINASERVICE_EXCEPTION!= null) {
            throw MACCHINASERVICE_EXCEPTION;
        }
        return MACCHINASERVICE_WSDL_LOCATION;
    }

}
