
package it.car2go.servant.utente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UtenteService", targetNamespace = "http://utente.servant.car2go.it/", wsdlLocation = "http://imac-di-francesco.local:8080/car2go-soapws/UtenteService?wsdl")
public class UtenteService
    extends Service
{

    private final static URL UTENTESERVICE_WSDL_LOCATION;
    private final static WebServiceException UTENTESERVICE_EXCEPTION;
    private final static QName UTENTESERVICE_QNAME = new QName("http://utente.servant.car2go.it/", "UtenteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://imac-di-francesco.local:8080/car2go-soapws/UtenteService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UTENTESERVICE_WSDL_LOCATION = url;
        UTENTESERVICE_EXCEPTION = e;
    }

    public UtenteService() {
        super(__getWsdlLocation(), UTENTESERVICE_QNAME);
    }

    public UtenteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UTENTESERVICE_QNAME, features);
    }

    public UtenteService(URL wsdlLocation) {
        super(wsdlLocation, UTENTESERVICE_QNAME);
    }

    public UtenteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UTENTESERVICE_QNAME, features);
    }

    public UtenteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UtenteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UtenteServant
     */
    @WebEndpoint(name = "UtenteServantPort")
    public UtenteServant getUtenteServantPort() {
        return super.getPort(new QName("http://utente.servant.car2go.it/", "UtenteServantPort"), UtenteServant.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UtenteServant
     */
    @WebEndpoint(name = "UtenteServantPort")
    public UtenteServant getUtenteServantPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://utente.servant.car2go.it/", "UtenteServantPort"), UtenteServant.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UTENTESERVICE_EXCEPTION!= null) {
            throw UTENTESERVICE_EXCEPTION;
        }
        return UTENTESERVICE_WSDL_LOCATION;
    }

}
