
package it.car2go.servant.ruolo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RuoloService", targetNamespace = "http://ruolo.servant.car2go.it/", wsdlLocation = "http://imac-di-francesco.local:8080/car2go-soapws/RuoloService?wsdl")
public class RuoloService
    extends Service
{

    private final static URL RUOLOSERVICE_WSDL_LOCATION;
    private final static WebServiceException RUOLOSERVICE_EXCEPTION;
    private final static QName RUOLOSERVICE_QNAME = new QName("http://ruolo.servant.car2go.it/", "RuoloService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://imac-di-francesco.local:8080/car2go-soapws/RuoloService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RUOLOSERVICE_WSDL_LOCATION = url;
        RUOLOSERVICE_EXCEPTION = e;
    }

    public RuoloService() {
        super(__getWsdlLocation(), RUOLOSERVICE_QNAME);
    }

    public RuoloService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RUOLOSERVICE_QNAME, features);
    }

    public RuoloService(URL wsdlLocation) {
        super(wsdlLocation, RUOLOSERVICE_QNAME);
    }

    public RuoloService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RUOLOSERVICE_QNAME, features);
    }

    public RuoloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RuoloService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RuoloServant
     */
    @WebEndpoint(name = "RuoloServantPort")
    public RuoloServant getRuoloServantPort() {
        return super.getPort(new QName("http://ruolo.servant.car2go.it/", "RuoloServantPort"), RuoloServant.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RuoloServant
     */
    @WebEndpoint(name = "RuoloServantPort")
    public RuoloServant getRuoloServantPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ruolo.servant.car2go.it/", "RuoloServantPort"), RuoloServant.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RUOLOSERVICE_EXCEPTION!= null) {
            throw RUOLOSERVICE_EXCEPTION;
        }
        return RUOLOSERVICE_WSDL_LOCATION;
    }

}
