
package it.car2go.servant.ruolo;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RuoloServant", targetNamespace = "http://ruolo.servant.car2go.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RuoloServant {


    /**
     * 
     * @return
     *     returns java.util.List<it.car2go.servant.ruolo.Ruolo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRuoli", targetNamespace = "http://ruolo.servant.car2go.it/", className = "it.car2go.servant.ruolo.GetRuoli")
    @ResponseWrapper(localName = "getRuoliResponse", targetNamespace = "http://ruolo.servant.car2go.it/", className = "it.car2go.servant.ruolo.GetRuoliResponse")
    @Action(input = "http://ruolo.servant.car2go.it/RuoloServant/getRuoliRequest", output = "http://ruolo.servant.car2go.it/RuoloServant/getRuoliResponse")
    public List<Ruolo> getRuoli();

    /**
     * 
     * @param arg0
     * @return
     *     returns it.car2go.servant.ruolo.Ruolo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRuoloById", targetNamespace = "http://ruolo.servant.car2go.it/", className = "it.car2go.servant.ruolo.GetRuoloById")
    @ResponseWrapper(localName = "getRuoloByIdResponse", targetNamespace = "http://ruolo.servant.car2go.it/", className = "it.car2go.servant.ruolo.GetRuoloByIdResponse")
    @Action(input = "http://ruolo.servant.car2go.it/RuoloServant/getRuoloByIdRequest", output = "http://ruolo.servant.car2go.it/RuoloServant/getRuoloByIdResponse")
    public Ruolo getRuoloById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns it.car2go.servant.ruolo.Ruolo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRuoloByNome", targetNamespace = "http://ruolo.servant.car2go.it/", className = "it.car2go.servant.ruolo.GetRuoloByNome")
    @ResponseWrapper(localName = "getRuoloByNomeResponse", targetNamespace = "http://ruolo.servant.car2go.it/", className = "it.car2go.servant.ruolo.GetRuoloByNomeResponse")
    @Action(input = "http://ruolo.servant.car2go.it/RuoloServant/getRuoloByNomeRequest", output = "http://ruolo.servant.car2go.it/RuoloServant/getRuoloByNomeResponse")
    public Ruolo getRuoloByNome(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "aggiornaRuolo", targetNamespace = "http://ruolo.servant.car2go.it/", className = "it.car2go.servant.ruolo.AggiornaRuolo")
    @ResponseWrapper(localName = "aggiornaRuoloResponse", targetNamespace = "http://ruolo.servant.car2go.it/", className = "it.car2go.servant.ruolo.AggiornaRuoloResponse")
    @Action(input = "http://ruolo.servant.car2go.it/RuoloServant/aggiornaRuoloRequest", output = "http://ruolo.servant.car2go.it/RuoloServant/aggiornaRuoloResponse")
    public void aggiornaRuolo(
        @WebParam(name = "arg0", targetNamespace = "")
        Ruolo arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "salvaRuolo", targetNamespace = "http://ruolo.servant.car2go.it/", className = "it.car2go.servant.ruolo.SalvaRuolo")
    @ResponseWrapper(localName = "salvaRuoloResponse", targetNamespace = "http://ruolo.servant.car2go.it/", className = "it.car2go.servant.ruolo.SalvaRuoloResponse")
    @Action(input = "http://ruolo.servant.car2go.it/RuoloServant/salvaRuoloRequest", output = "http://ruolo.servant.car2go.it/RuoloServant/salvaRuoloResponse")
    public void salvaRuolo(
        @WebParam(name = "arg0", targetNamespace = "")
        Ruolo arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "cancellaRuolo", targetNamespace = "http://ruolo.servant.car2go.it/", className = "it.car2go.servant.ruolo.CancellaRuolo")
    @ResponseWrapper(localName = "cancellaRuoloResponse", targetNamespace = "http://ruolo.servant.car2go.it/", className = "it.car2go.servant.ruolo.CancellaRuoloResponse")
    @Action(input = "http://ruolo.servant.car2go.it/RuoloServant/cancellaRuoloRequest", output = "http://ruolo.servant.car2go.it/RuoloServant/cancellaRuoloResponse")
    public void cancellaRuolo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
