
package it.car2go.servant.macchina;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MacchinaServant", targetNamespace = "http://macchina.servant.car2go.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MacchinaServant {


    /**
     * 
     * @return
     *     returns java.util.List<it.car2go.servant.macchina.Macchina>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMacchineNonPrenotate", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.GetMacchineNonPrenotate")
    @ResponseWrapper(localName = "getMacchineNonPrenotateResponse", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.GetMacchineNonPrenotateResponse")
    @Action(input = "http://macchina.servant.car2go.it/MacchinaServant/getMacchineNonPrenotateRequest", output = "http://macchina.servant.car2go.it/MacchinaServant/getMacchineNonPrenotateResponse")
    public List<Macchina> getMacchineNonPrenotate();

    /**
     * 
     * @param arg0
     * @return
     *     returns it.car2go.servant.macchina.Macchina
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMacchina", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.GetMacchina")
    @ResponseWrapper(localName = "getMacchinaResponse", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.GetMacchinaResponse")
    @Action(input = "http://macchina.servant.car2go.it/MacchinaServant/getMacchinaRequest", output = "http://macchina.servant.car2go.it/MacchinaServant/getMacchinaResponse")
    public Macchina getMacchina(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateMacchina", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.UpdateMacchina")
    @ResponseWrapper(localName = "updateMacchinaResponse", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.UpdateMacchinaResponse")
    @Action(input = "http://macchina.servant.car2go.it/MacchinaServant/updateMacchinaRequest", output = "http://macchina.servant.car2go.it/MacchinaServant/updateMacchinaResponse")
    public void updateMacchina(
        @WebParam(name = "arg0", targetNamespace = "")
        Macchina arg0);

    /**
     * 
     * @return
     *     returns java.util.List<it.car2go.servant.macchina.Macchina>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMacchine", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.GetMacchine")
    @ResponseWrapper(localName = "getMacchineResponse", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.GetMacchineResponse")
    @Action(input = "http://macchina.servant.car2go.it/MacchinaServant/getMacchineRequest", output = "http://macchina.servant.car2go.it/MacchinaServant/getMacchineResponse")
    public List<Macchina> getMacchine();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addMacchina", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.AddMacchina")
    @ResponseWrapper(localName = "addMacchinaResponse", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.AddMacchinaResponse")
    @Action(input = "http://macchina.servant.car2go.it/MacchinaServant/addMacchinaRequest", output = "http://macchina.servant.car2go.it/MacchinaServant/addMacchinaResponse")
    public void addMacchina(
        @WebParam(name = "arg0", targetNamespace = "")
        Macchina arg0);

    /**
     * 
     * @return
     *     returns java.util.List<it.car2go.servant.macchina.Macchina>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMacchineSenzaBenzina", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.GetMacchineSenzaBenzina")
    @ResponseWrapper(localName = "getMacchineSenzaBenzinaResponse", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.GetMacchineSenzaBenzinaResponse")
    @Action(input = "http://macchina.servant.car2go.it/MacchinaServant/getMacchineSenzaBenzinaRequest", output = "http://macchina.servant.car2go.it/MacchinaServant/getMacchineSenzaBenzinaResponse")
    public List<Macchina> getMacchineSenzaBenzina();

    /**
     * 
     * @return
     *     returns java.util.List<it.car2go.servant.macchina.Macchina>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMacchineSporcheInterno", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.GetMacchineSporcheInterno")
    @ResponseWrapper(localName = "getMacchineSporcheInternoResponse", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.GetMacchineSporcheInternoResponse")
    @Action(input = "http://macchina.servant.car2go.it/MacchinaServant/getMacchineSporcheInternoRequest", output = "http://macchina.servant.car2go.it/MacchinaServant/getMacchineSporcheInternoResponse")
    public List<Macchina> getMacchineSporcheInterno();

    /**
     * 
     * @return
     *     returns java.util.List<it.car2go.servant.macchina.Macchina>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMacchineSporcheEsterno", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.GetMacchineSporcheEsterno")
    @ResponseWrapper(localName = "getMacchineSporcheEsternoResponse", targetNamespace = "http://macchina.servant.car2go.it/", className = "it.car2go.servant.macchina.GetMacchineSporcheEsternoResponse")
    @Action(input = "http://macchina.servant.car2go.it/MacchinaServant/getMacchineSporcheEsternoRequest", output = "http://macchina.servant.car2go.it/MacchinaServant/getMacchineSporcheEsternoResponse")
    public List<Macchina> getMacchineSporcheEsterno();

}
