
package it.car2go.servant.utente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UtenteServant", targetNamespace = "http://utente.servant.car2go.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtenteServant {


    /**
     * 
     * @param arg0
     * @return
     *     returns it.car2go.servant.utente.Utente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUtenteById", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.GetUtenteById")
    @ResponseWrapper(localName = "getUtenteByIdResponse", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.GetUtenteByIdResponse")
    @Action(input = "http://utente.servant.car2go.it/UtenteServant/getUtenteByIdRequest", output = "http://utente.servant.car2go.it/UtenteServant/getUtenteByIdResponse")
    public Utente getUtenteById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns it.car2go.servant.utente.Utente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUtenteByUsername", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.GetUtenteByUsername")
    @ResponseWrapper(localName = "getUtenteByUsernameResponse", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.GetUtenteByUsernameResponse")
    @Action(input = "http://utente.servant.car2go.it/UtenteServant/getUtenteByUsernameRequest", output = "http://utente.servant.car2go.it/UtenteServant/getUtenteByUsernameResponse")
    public Utente getUtenteByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns it.car2go.servant.utente.Utente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUtenteByUsernamePassword", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.GetUtenteByUsernamePassword")
    @ResponseWrapper(localName = "getUtenteByUsernamePasswordResponse", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.GetUtenteByUsernamePasswordResponse")
    @Action(input = "http://utente.servant.car2go.it/UtenteServant/getUtenteByUsernamePasswordRequest", output = "http://utente.servant.car2go.it/UtenteServant/getUtenteByUsernamePasswordResponse")
    public Utente getUtenteByUsernamePassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<it.car2go.servant.utente.Utente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUtenti", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.GetUtenti")
    @ResponseWrapper(localName = "getUtentiResponse", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.GetUtentiResponse")
    @Action(input = "http://utente.servant.car2go.it/UtenteServant/getUtentiRequest", output = "http://utente.servant.car2go.it/UtenteServant/getUtentiResponse")
    public List<Utente> getUtenti();

    /**
     * 
     * @param arg0
     * @return
     *     returns it.car2go.servant.utente.Ruolo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRuoloUtenteById", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.GetRuoloUtenteById")
    @ResponseWrapper(localName = "getRuoloUtenteByIdResponse", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.GetRuoloUtenteByIdResponse")
    @Action(input = "http://utente.servant.car2go.it/UtenteServant/getRuoloUtenteByIdRequest", output = "http://utente.servant.car2go.it/UtenteServant/getRuoloUtenteByIdResponse")
    public Ruolo getRuoloUtenteById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "salvaUtente", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.SalvaUtente")
    @ResponseWrapper(localName = "salvaUtenteResponse", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.SalvaUtenteResponse")
    @Action(input = "http://utente.servant.car2go.it/UtenteServant/salvaUtenteRequest", output = "http://utente.servant.car2go.it/UtenteServant/salvaUtenteResponse")
    public void salvaUtente(
        @WebParam(name = "arg0", targetNamespace = "")
        Utente arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "cancellaUtente", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.CancellaUtente")
    @ResponseWrapper(localName = "cancellaUtenteResponse", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.CancellaUtenteResponse")
    @Action(input = "http://utente.servant.car2go.it/UtenteServant/cancellaUtenteRequest", output = "http://utente.servant.car2go.it/UtenteServant/cancellaUtenteResponse")
    public void cancellaUtente(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "aggiornaUtente", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.AggiornaUtente")
    @ResponseWrapper(localName = "aggiornaUtenteResponse", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.AggiornaUtenteResponse")
    @Action(input = "http://utente.servant.car2go.it/UtenteServant/aggiornaUtenteRequest", output = "http://utente.servant.car2go.it/UtenteServant/aggiornaUtenteResponse")
    public void aggiornaUtente(
        @WebParam(name = "arg0", targetNamespace = "")
        Utente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificaPresenzaUsername", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.VerificaPresenzaUsername")
    @ResponseWrapper(localName = "verificaPresenzaUsernameResponse", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.VerificaPresenzaUsernameResponse")
    @Action(input = "http://utente.servant.car2go.it/UtenteServant/verificaPresenzaUsernameRequest", output = "http://utente.servant.car2go.it/UtenteServant/verificaPresenzaUsernameResponse")
    public boolean verificaPresenzaUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<it.car2go.servant.utente.Utente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "elencoUtentiSemplici", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.ElencoUtentiSemplici")
    @ResponseWrapper(localName = "elencoUtentiSempliciResponse", targetNamespace = "http://utente.servant.car2go.it/", className = "it.car2go.servant.utente.ElencoUtentiSempliciResponse")
    @Action(input = "http://utente.servant.car2go.it/UtenteServant/elencoUtentiSempliciRequest", output = "http://utente.servant.car2go.it/UtenteServant/elencoUtentiSempliciResponse")
    public List<Utente> elencoUtentiSemplici(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
